require('./styles.scss');
import acrifolium from './assets/images/acrifolium.jpg';
import olivierAzevedoSmileNy from './assets/images/olivierAzevedoSmileNy.png';
import olivierAzevedoSmile from './assets/images/olivierAzevedoSmile.jpg';
import sdv from './assets/images/sdv.png';
import totalEnergies from './assets/images/total-energies.jpeg';
import m3Groupe from './assets/images/m3-groupe.jpeg';
import axa from './assets/images/axa.png';
import sgib from './assets/images/sgib.png';
import finexkap from './assets/images/finexkap.png';
import vinci from './assets/images/vinci.png';
import capgemini from './assets/images/capgemini.png';
